### ISSUE TITLE
Add New Hook: Key Listener

### ISSUE THREAD

**Issue by JCorrea13** [unosquare/uno-react#208]
This hook should add a listener keydown/keyup and remove it when the component gets unmounted.

Sample: 
`const onEscPress = (e): void => {
        if (e.key === 'Escape' && closeOnEscape) {
            onDismiss();
        }
    };

    React.useEffect(() => {
        document.addEventListener('keydown', onEscPress);

        return (): void => document.removeEventListener('keydown', onEscPress);
    }, []);`

**Comment by geoperez** [comment]
We same something similar, you can unify or depend one in another.

**Comment by geoperez** [comment]
Status? @JCorrea13
