### ISSUE TITLE
Creation of @types to expose exported elements

### ISSUE THREAD

**Issue by danilopatron** [unosquare/uno-react#31]
Currently we see this error message into the vs code

![image](https://user-images.githubusercontent.com/12257713/53053537-4c6d0600-3467-11e9-8d1b-9d37ab236172.png)

And this is the suggestions:

![image](https://user-images.githubusercontent.com/12257713/53053565-5a228b80-3467-11e9-9130-d434f3ffeb11.png)

But this should be done from the library.

cc. @AnyxLeo

**Comment by geoperez** [comment]
I like the idea to include the types. Thanks for the heads up!

**Comment by geoperez** [comment]
I'm publishing now the index.d.ts in the npm package. I just need to define correct typing.

@danilopatron you can update the package and remove the typings in MariaReports.
